# ---
# apiVersion: admissionregistration.k8s.io/v1beta1
# kind: ValidatingWebhookConfiguration
# metadata:
#   name: net-attach-def-admission-controller-isolating-config
# webhooks:
#   - name: net-attach-def-admission-controller-isolating-config.k8s.io
#     clientConfig:
#       service:
#         name: net-attach-def-admission-controller-service
#         namespace: ${NAMESPACE}
#         path: "/isolate"
#       caBundle: ${CA_BUNDLE}
#     rules:
#       - operations: [ "CREATE" ]
#         apiGroups: ["apps", ""]
#         apiVersions: ["v1"]
#         resources: ["pods"]
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: net-attach-def-admission-controller-validating-config
webhooks:
  - name: net-attach-def-admission-controller-validating-config.k8s.io
    clientConfig:
      service:
        name: net-attach-def-admission-controller-service
        namespace: ${NAMESPACE}
        path: "/validate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["k8s.cni.cncf.io"]
        apiVersions: ["v1"]
        resources: ["network-attachment-definitions"]
